// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnTkyE0CYQOn0EGt0gD_nA_EV3u7dIbAw',
    appId: '1:1009832925247:web:e4ddf6e49307bdd1e1808a',
    messagingSenderId: '1009832925247',
    projectId: 'lakbay-7dffa',
    authDomain: 'lakbay-7dffa.firebaseapp.com',
    databaseURL: 'https://lakbay-7dffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lakbay-7dffa.appspot.com',
    measurementId: 'G-5ZBGL9DX7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDDtECiqfZkN4_1EYuLDa_QhsQiFmvEs',
    appId: '1:1009832925247:android:4af467d0323b5dc7e1808a',
    messagingSenderId: '1009832925247',
    projectId: 'lakbay-7dffa',
    databaseURL: 'https://lakbay-7dffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lakbay-7dffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5HRworXxSjeoWGsKi4DsP4t6uNrZHzVo',
    appId: '1:1009832925247:ios:d5df39efbd9cd32ae1808a',
    messagingSenderId: '1009832925247',
    projectId: 'lakbay-7dffa',
    databaseURL: 'https://lakbay-7dffa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lakbay-7dffa.appspot.com',
    iosClientId: '1009832925247-sq3om2mdrl6v6bmpo4b4rporl6d1b5vs.apps.googleusercontent.com',
    iosBundleId: 'com.example.lakbay',
  );
}
